import {Request, Response, NextFunction} from 'express'
import categoriesService from '../services/categories.service';
import {sendJsonSuccess} from '../helpers/responseHandler'

const findAll =  (req: Request, res: Response, next: NextFunction)=>{
  console.log('<<=== üöÄfindAll  ===>>',findAll);
  try {
    // L·∫•y data t·ª´ l·ªõp service
    const categories = categoriesService.findAll();
    //Tr·∫£ l·∫°i cho client
    // res.status(200).json({
    //   data: categories
    // })
    sendJsonSuccess(res, "success")(categories)

  } catch (error) {
    next(error)
  }
  

}

const findById = (req: Request, res: Response, next: NextFunction)=>{
  try {
    const {id} = req.params;
  
    const category = categoriesService.findById(parseInt(id))
    
    res.status(200).json({
    data: category
    })
  } catch (error) {
    next(error)
  }
}

const createRecord =  (req: Request, res: Response, next: NextFunction)=>{
 try {
  console.log('<<=== üöÄ req.body ===>>',req.body);
  
  const category =  categoriesService.createRecord(req.body)
  
  console.log('<<=== üöÄ category controller ===>>',category);

  res.status(201).json({
    data: category
  })
 } catch (error) {
  next(error)
 }
  
}

const updateById = (req: Request, res: Response, next: NextFunction)=>{
  try {
    const {id} = req.params

    const category = categoriesService.updateById(parseInt(id), req.body)

    //Th√†nh c√¥ng
    res.status(200).json({
      data: category
    })

  } catch (error) {
    //Chuy·ªÉn l·ªói qua cho handler error trong app.ts x·ª≠ l√Ω
    next(error)
  }
  
}

const deleteById = (req: Request, res: Response, next: NextFunction)=>{
  try {
    const {id} = req.params
    
    const category = categoriesService.deleteById(parseInt(id))

    res.status(200).json({
        //Tr·∫£ v·ªÅ ph·∫ßn t·ª≠ v·ª´a ƒë∆∞·ª£c x√≥a
        data: category
    })

  } catch (error) {
    next(error)
  }
}

export default {
  findAll,
  findById,
  createRecord,
  updateById,
  deleteById
}